const express = require('express');
const axios = require('axios');
const router = express.Router();
const { getTokens } = require('../utils/tokenStore');
const { createRepo, pushWebsite } = require('../services/githubService');
const { createDeployment } = require('../services/vercelService');

// POST /project/create-and-deploy
router.post('/create-and-deploy', async (req, res) => {
  const { repoName, websiteHtml, files } = req.body;
  let framework = req.body.framework;
  
  const githubToken = req.headers['x-github-token'] || req.body.githubToken;
  const vercelToken = req.headers['x-vercel-token'] || req.body.vercelToken;
  const githubUsername = req.headers['x-github-username'] || req.body.githubUsername;
  const explicitUserId = req.headers['x-user-id'] || req.body.userId;

  let tokens = {};
  if (githubToken && vercelToken) {
    tokens = { githubToken, vercelToken, githubUsername };
  } else {
    tokens = await getTokens(req.session, explicitUserId);
    // Fallback to reading headers if session didn't have them but headers did
    if (!tokens.githubToken && githubToken) tokens.githubToken = githubToken;
    if (!tokens.githubUsername && githubUsername) tokens.githubUsername = githubUsername;
    if (!tokens.vercelToken && vercelToken) tokens.vercelToken = vercelToken;
  }
  
  if (!tokens.githubToken) {
    return res.status(401).json({ error: 'GitHub not connected' });
  }
  if (!tokens.vercelToken) {
    return res.status(401).json({ error: 'Vercel not connected' });
  }

  try {
    // 1. Create GitHub repo (or retrieve if already exists)
    let repo;
    try {
      repo = await createRepo(tokens.githubToken, repoName);
    } catch (error) {
      if (error.response && error.response.status === 422) {
        // Repository already exists, fetch it
        const username = tokens.githubUsername;
        const repoResponse = await axios.get(`https://api.github.com/repos/${username}/${repoName}`, {
          headers: { Authorization: `Bearer ${tokens.githubToken}` }
        });
        repo = repoResponse.data;
      } else {
        throw error;
      }
    }
    const repoFullName = repo.full_name; // e.g., "username/mysite"
    const repoId = repo.id;

    // 2. Prepare files to push
    let projectFiles = files;
    if (!projectFiles && websiteHtml) {
      projectFiles = [{ path: 'index.html', content: websiteHtml }];
    }

    if (!projectFiles || projectFiles.length === 0) {
      return res.status(400).json({ error: 'No files or HTML content provided' });
    }

    // Framework auto-detection
    if (!framework) {
      if (projectFiles.some(f => f.path.startsWith('lib/') || f.path === 'pubspec.yaml')) {
        framework = 'flutter';
      } else if (projectFiles.some(f => f.path === 'package.json')) {
        framework = 'react';
      } else {
        framework = 'html';
      }
    }

    // Auto-inject vercel.json rewrite for SPA routing on Flutter/React
    if (framework === 'flutter' || framework === 'react') {
      const hasVercelJson = projectFiles.some(f => f.path.toLowerCase() === 'vercel.json');
      if (!hasVercelJson) {
        projectFiles.push({
          path: 'vercel.json',
          content: JSON.stringify({
            rewrites: [
              {
                source: '/(.*)',
                destination: '/index.html'
              }
            ]
          }, null, 2)
        });
      }
    }

    // Auto-inject Flutter template files if framework is flutter
    if (framework === 'flutter') {
      // Validate that at least some source files under lib/ exist
      const hasLibFiles = projectFiles.some(f => f.path.startsWith('lib/'));
      if (!hasLibFiles) {
        return res.status(400).json({ error: 'Flutter project structure invalid: missing lib/ directory files' });
      }

      // Check & Inject pubspec.yaml
      const hasPubspec = projectFiles.some(f => f.path.toLowerCase() === 'pubspec.yaml');
      if (!hasPubspec) {
        projectFiles.push({
          path: 'pubspec.yaml',
          content: `name: revochamp_generated_app
description: "A Flutter Web project generated by Revochamp."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.5.1
flutter:
  uses-material-design: true
`
        });
      }

      // Check & Inject analysis_options.yaml
      const hasAnalysisOptions = projectFiles.some(f => f.path.toLowerCase() === 'analysis_options.yaml');
      if (!hasAnalysisOptions) {
        projectFiles.push({
          path: 'analysis_options.yaml',
          content: `include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: false
`
        });
      }

      // Check & Inject vercel-build.sh
      const hasVercelBuildSh = projectFiles.some(f => f.path.toLowerCase() === 'vercel-build.sh');
      if (!hasVercelBuildSh) {
        projectFiles.push({
          path: 'vercel-build.sh',
          content: `#!/bin/bash
set -e
echo "=== Starting Flutter Web Build on Vercel ==="
if [ ! -d "flutter" ]; then
  echo "Cloning Flutter SDK..."
  git clone https://github.com/flutter/flutter.git -b stable --depth 1
else
  echo "Flutter SDK already exists."
fi
export PATH="$PATH:$PWD/flutter/bin"
echo "Configuring Flutter..."
flutter config --enable-web
flutter doctor
echo "Installing dependencies..."
flutter pub get
echo "Building web project..."
flutter build web --release
echo "=== Build Completed ==="
`
        });
      }

      // Check & Inject web/index.html
      const hasIndexHtml = projectFiles.some(f => f.path.toLowerCase() === 'web/index.html');
      if (!hasIndexHtml) {
        projectFiles.push({
          path: 'web/index.html',
          content: `<!DOCTYPE html>
<html>
<head>
  <base href="/">
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A Flutter Web project generated by Revochamp.">
  <title>Revochamp App</title>
  <link rel="manifest" href="manifest.json">
  <script src="flutter_bootstrap.js" async></script>
</head>
<body>
</body>
</html>
`
        });
      }

      // Check & Inject web/flutter_bootstrap.js
      const hasBootstrapJs = projectFiles.some(f => f.path.toLowerCase() === 'web/flutter_bootstrap.js');
      if (!hasBootstrapJs) {
        projectFiles.push({
          path: 'web/flutter_bootstrap.js',
          content: `{{flutter_js}}
{{flutter_build_config}}
_flutter.loader.load();
`
        });
      }

      // Check & Inject web/manifest.json
      const hasManifest = projectFiles.some(f => f.path.toLowerCase() === 'web/manifest.json');
      if (!hasManifest) {
        projectFiles.push({
          path: 'web/manifest.json',
          content: JSON.stringify({
            name: "revochamp_generated_app",
            short_name: "revochamp",
            start_url: ".",
            display: "standalone",
            background_color: "#ffffff",
            theme_color: "#0175C2",
            description: "A Flutter Web project generated by Revochamp."
          }, null, 2)
        });
      }
    }

    // Push website code
    await pushWebsite(tokens.githubToken, repoFullName, projectFiles);

    // 3. Trigger Vercel deployment
    const defaultBranch = repo.default_branch || 'main';
    const deployment = await createDeployment(tokens.vercelToken, repoFullName, repoId, repoName, framework, defaultBranch);

    res.json({
      repoUrl: repo.html_url,
      deploymentUrl: `https://${deployment.url}`,
      deploymentId: deployment.id
    });
  } catch (error) {
    const errorDetails = error.response?.data || error.message;
    console.error('Deployment error:', errorDetails);
    res.status(500).json({ 
      error: 'Deployment failed', 
      details: errorDetails 
    });
  }
});

// GET /deployment/status/:deploymentId
router.get('/deployment/status/:deploymentId', async (req, res) => {
  const { deploymentId } = req.params;
  
  const vercelToken = req.headers['x-vercel-token'] || req.query.vercelToken;
  const explicitUserId = req.headers['x-user-id'] || req.query.userId;
  
  let tokens = {};
  if (vercelToken) {
    tokens = { vercelToken };
  } else {
    tokens = await getTokens(req.session, explicitUserId);
    if (!tokens.vercelToken && vercelToken) tokens.vercelToken = vercelToken;
  }

  if (!tokens.vercelToken) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  const { getDeploymentStatus } = require('../services/vercelService');
  const status = await getDeploymentStatus(tokens.vercelToken, deploymentId);
  res.json({ status });
});

// GET /deployment/logs/:deploymentId
router.get('/deployment/logs/:deploymentId', async (req, res) => {
  const { deploymentId } = req.params;
  
  const vercelToken = req.headers['x-vercel-token'] || req.query.vercelToken;
  const explicitUserId = req.headers['x-user-id'] || req.query.userId;
  
  let tokens = {};
  if (vercelToken) {
    tokens = { vercelToken };
  } else {
    tokens = await getTokens(req.session, explicitUserId);
    if (!tokens.vercelToken && vercelToken) tokens.vercelToken = vercelToken;
  }

  if (!tokens.vercelToken) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  try {
    const response = await axios.get(`https://api.vercel.com/v2/deployments/${deploymentId}/events`, {
      headers: { Authorization: `Bearer ${tokens.vercelToken}` }
    });
    res.json(response.data);
  } catch (error) {
    console.error(`Failed to fetch logs for deployment ${deploymentId}:`, error.response?.data || error.message);
    res.status(500).json({ error: 'Failed to fetch logs' });
  }
});

module.exports = router;